### ISSUE TITLE
Cannot Install on Ubuntu 16.04

### ISSUE THREAD

**Issue by Leo428** [robotpy/robotpy-eclipse-plugins#11]
Cannot complete the install because one or more required items could not be found.
  Software being installed: Robot Python Development 2015.0.8 (io.github.robotpy.plugins.robotpy.feature.feature.group 2015.0.8)

**Comment by Twinters007** [comment]
<img width="368" alt="image" src="https://cloud.githubusercontent.com/assets/6132901/24325224/8c918750-116a-11e7-9718-0bf6328e20a4.png">

**Comment by virtuald** [comment]
Yeah, I should delete these or make it more obvious that you shouldn't use them.

**Comment by Twinters007** [comment]
Delete
