### ISSUE TITLE
Plugin can no longer be downloaded from the update site

### ISSUE THREAD

**Issue by RVR87Programming** [robotpy/robotpy-eclipse-plugins#17]
Manual installs using the dev testing instructions in the readme still work (assuming the dependency issues can be worked out #15 ), however the plugin does take a while to compile manually and the update site integrates better with eclipse. For this to be fixed, the issue referenced above likely needs to be fixed first.

**Comment by virtuald** [comment]
I'll try to address this tonight, sorry for neglecting this.

**Comment by RVR87Programming** [comment]
This is now fixed
